// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diupktpzfugozipeeshj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdXBrdHB6ZnVnb3ppcGVlc2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDc3NzksImV4cCI6MjA2OTkyMzc3OX0.x0vE89-P-sBpS7xyvUdMErHGQgrBq1DzawcbTlXe3Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});